# Generated by Django 3.0.7 on 2020-06-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='El Nombre')),
                ('edad', models.CharField(max_length=30, verbose_name='El Nombre')),
                ('apellido_mater', models.CharField(max_length=30, verbose_name='El Apellido materno')),
                ('apellido_pater', models.CharField(max_length=30, verbose_name='El Apellido Paterno')),
                ('direccion', models.CharField(max_length=50, verbose_name='La Direccion')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='El mail')),
                ('telefono', models.CharField(max_length=13, verbose_name='El Telefono')),
                ('comentario', models.CharField(max_length=30, verbose_name='El Comentario')),
            ],
        ),
    ]
