# Generated by Django 3.0.7 on 2020-06-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jorqueraWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='edad',
            field=models.CharField(max_length=30, verbose_name='La Edad'),
        ),
    ]
